################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c 

OBJS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.o 

C_DEPS += \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d \
./Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_cortex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_dma_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_flash_ramfunc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_gpio.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_i2c_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pcd_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pcd_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_pwr_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_hal_tim_ex.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.o: C:/Users/Thomas/Dropbox/_Uni\ AAU/P9/Self-driving\ RC\ car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_usb.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 '-D__weak=__attribute__((weak))' -DHAL_UART_MODULE_ENABLED '-D__packed=__attribute__((__packed__))' -DUSE_HAL_DRIVER -DSTM32F405xx -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/VL53L0X" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Libraries/XV11_LiDAR" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/include" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS" -I"C:/Users/Thomas/Dropbox/_Uni AAU/P9/Self-driving RC car/STM32/Projects/JetsonCar_STM32/Drivers/CMSIS/Include"  -Og -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"Drivers/STM32F4xx_HAL_Driver/stm32f4xx_ll_usb.d" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


